
// 完全にユニークで多様な記事データを生成する関数
function generateUniqueArticles() {
  const allArticles = [];

  // ビジネス記事60本 - 完全にユニークなデータ
  const businessTitles = [
    "Amazon、日本で物流センター10拠点新設。配送時間短縮と雇用創出で地域経済活性化",
    "トヨタ、水素エンジン車の量産化を発表。2026年から商用車市場に本格参入",
    "ソフトバンク、6G通信技術の実証実験開始。2030年の商用化に向けて加速",
    "楽天、ドローン配送サービスを全国展開。過疎地域の物流課題解決に貢献",
    "三菱商事、洋上風力発電事業に2兆円投資。再生可能エネルギー分野を強化",
    "パナソニック、全固体電池の量産技術確立。EV業界に革命をもたらす可能性",
    "NTTドコモ、メタバース事業に本格参入。仮想空間での新サービス展開",
    "キーエンス、AI搭載検査装置で世界シェア拡大。製造業のDX化を牽引",
    "ファーストリテイリング、サステナブル素材100%達成。環境配慮型ファッションを推進",
    "JR東日本、自動運転列車の実用化へ。安全性向上と運行効率化を実現",
    "セブン&アイ、無人店舗技術を全店導入。小売業界のデジタル変革を加速",
    "日立製作所、量子コンピューター事業に参入。次世代計算技術の開発を推進",
    "KDDI、衛星通信サービスを開始。災害時の通信インフラ強化を図る",
    "イオン、植物工場事業を拡大。食料自給率向上と安定供給を目指す",
    "三井物産、カーボンニュートラル燃料の開発加速。脱炭素社会実現に貢献",
    "富士通、AIチップの自社開発を発表。半導体事業への本格復帰",
    "住友商事、リチウム採掘事業に参入。EV普及に伴う需要増に対応",
    "丸紅、洋上太陽光発電プロジェクト開始。新たな再エネ分野を開拓",
    "伊藤忠商事、食品ロス削減AIシステム導入。サプライチェーン最適化を実現",
    "双日、水素製造プラント建設に着手。クリーンエネルギー事業を強化",
    "オリックス、バイオマス発電事業を拡大。循環型社会の構築に貢献",
    "三菱重工、小型原子炉の開発を推進。次世代エネルギー技術に挑戦",
    "川崎重工、水素航空機エンジン開発。航空業界の脱炭素化を牽引",
    "IHI、宇宙デブリ除去技術を実用化。宇宙環境保護に貢献",
    "コマツ、建設機械の完全自動化実現。建設現場の生産性向上を支援",
    "クボタ、スマート農業ソリューション展開。農業の効率化と持続可能性を追求",
    "ダイキン、次世代冷媒技術を開発。地球温暖化対策に貢献",
    "村田製作所、6G対応部品の量産開始。次世代通信技術の基盤を支える",
    "京セラ、太陽光発電効率50%達成。再生可能エネルギーの可能性を拡大",
    "TDK、全固体電池材料の革新技術開発。エネルギー貯蔵の未来を変える",
    "シャープ、8K映像技術を医療分野に応用。精密診断技術の向上に貢献",
    "東芝、次世代半導体製造装置を開発。半導体産業の競争力強化",
    "富士フイルム、再生医療技術の実用化推進。医療分野での新展開",
    "オムロン、AI搭載ロボット技術を進化。製造業の自動化を加速",
    "ファナック、協働ロボットの新シリーズ発表。人とロボットの共存を実現",
    "安川電機、産業用ロボットのAI化推進。スマートファクトリーを支援",
    "日本電産、EV用モーターの革新技術開発。電動化社会の基盤技術を提供",
    "ニデック、精密減速機の新技術確立。ロボット産業の発展に貢献",
    "THK、直動システムの高精度化実現。製造業の品質向上を支援",
    "SMC、省エネ空圧機器の開発推進。工場の環境負荷削減に貢献",
    "横河電機、プラント運転の完全自動化。化学工業の安全性向上を実現",
    "アズビル、ビル管理システムのAI化。エネルギー効率の最適化を図る",
    "キッツ、水素対応バルブ技術を開発。水素社会の基盤インフラを支える",
    "荏原製作所、海水淡水化技術を革新。水資源問題の解決に貢献",
    "クラレ、バイオプラスチック量産技術確立。持続可能な素材開発を推進",
    "東レ、炭素繊維の新用途開発。軽量化技術で産業革新を支援",
    "帝人、リサイクル繊維技術を確立。循環型経済の実現に貢献",
    "旭化成、バイオ医薬品製造技術を革新。医療の質向上に貢献",
    "三菱ケミカル、次世代電池材料を開発。エネルギー貯蔵技術を進化",
    "住友化学、農薬のデジタル化推進。精密農業の実現を支援",
    "JSR、半導体材料の新技術開発。次世代デバイスの基盤を支える",
    "信越化学、シリコン技術の革新推進。エレクトロニクス産業を支援",
    "日東電工、フレキシブル基板技術進化。ウェアラブルデバイスの発展に貢献",
    "積水化学、住宅用太陽光システム革新。エネルギー自給住宅を実現",
    "大日本印刷、電子ペーパー技術を進化。デジタルサイネージ市場を開拓",
    "凸版印刷、パッケージのスマート化推進。物流効率化に貢献",
    "リコー、オフィス業務の完全デジタル化。働き方改革を技術で支援",
    "コニカミノルタ、医療画像診断AI開発。診断精度の向上に貢献",
    "キヤノン、産業用3Dプリンター事業拡大。製造業の革新を支援",
    "ニコン、半導体露光装置の次世代技術開発。微細加工技術を進化"
  ];

  const businessImages = [
    "https://i.ytimg.com/vi/TUx-ljgB-5Q/maxresdefault.jpg",
    "https://i.ytimg.com/vi/-tmuiHm5sbc/maxresdefault.jpg",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi8swLSIY7OZyHm5N4Ps24jNVHZ-BKiWNIOUWovWSSqF7VY0UFz4EM36cdqi56XqeVs-z8DkXS-bx5_Hf0l9DaLoV_VwLOhTS8LRI-Tybvx5wZKVg4tW6eVHh0Ssi6sH-0SuE9VqD6BZeZJ70H1AhTZgvX4glRn432Wr7ho4bRETIJKpvlb4Mv3XZwhPWmR/s1920/SoftBank6G_Terahertz.jpg",
    "https://www.japantimes.co.jp/uploads/imported_images/uploads/2021/10/np_file_116188.jpeg",
    "https://thumbs.dreamstime.com/b/offshore-wind-farm-turbines-ocean-generative-ai-offshore-wind-farm-turbines-ocean-generative-ai-271582267.jpg",
    "https://www.enr.com/ext/resources/2022/07/14/Panasonic_Battery_Manufacturing_ENRweb.jpg?1657882532",
    "https://i.ytimg.com/vi/LS4vyjuUg0A/maxresdefault.jpg",
    "https://www.keyence.com/Images/lp_mvt_im_aoi_img_01_1463424.jpg",
    "https://www.uniqlo.com/jp/en/contents/sustainability/planet/img/article_reuniqlo.jpg",
    "https://i.ytimg.com/vi/0kKAAmEzTfE/maxresdefault.jpg",
    "https://i.ytimg.com/vi/3O7X4b2zcYQ/maxresdefault.jpg",
    "https://c8.alamy.com/comp/2M0BJBT/tokyo-japan-5th-dec-2022-this-picture-shows-japanese-electronics-giant-hitachis-experimental-model-of-quantum-computers-cryo-cooling-chamber-r-and-its-inside-image-l-at-hitachis-laboratory-in-tokyo-on-monday-december-4-2022-hitachi-introduced-their-latest-technologies-as-they-announced-the-companys-research-and-development-strategy-credit-yoshio-tsunodaafloalamy-live-news-2M0BJBT.jpg",
    "https://biz.kddi.com/content/dam/kddi-com/biz/service/satellite/inmarsat/images/card-satellite_inmarsat_satweb.jpg",
    "https://i.pinimg.com/originals/49/41/9e/49419ed632cb9b64ca2104cd0b94543c.jpg",
    "https://www.mitsubishi.com/en/csr/mpac/monitor/worldscope/202410/img/img-32.jpg",
    "https://images.saymedia-content.com/.image/t_share/MTc0NDg2OTE1ODk3MTA4MTAy/the-world-of-the-semiconductor-cleanroom.jpg",
    "https://i.pinimg.com/736x/83/51/1d/83511d045d461be74910cc00c8fd118f.jpg",
    "https://www.marubeni.com/en/business/power/2023power/img/img02.jpg",
    "https://i.ytimg.com/vi/W8XAIKvDq_E/maxresdefault.jpg",
    "https://www.sojitz.com/en/news/article/news_file/file/231115.png",
    "https://i.pinimg.com/originals/04/a1/0f/04a10fd2597ca8b0f93659074bc4e863.jpg",
    "https://pub.mdpi-res.com/energies/energies-16-05168/article_deploy/html/images/energies-16-05168-g004.png?1688538715",
    "https://global.kawasaki.com/en/corp/newsroom/news/images/news_211105-1.jpg",
    "https://i.pinimg.com/originals/a5/a1/24/a5a124766426f02f249b1044501fe151.jpg",
    "https://www.globalconstructionreview.com/wp-content/uploads/2021/08/846komatsu.jpg",
    "https://www.kubota.com/products/tractor/images/img_technologies_03.jpg",
    "https://www.daikin.com/-/media/Project/Daikin/daikin_com/corporate/why_daikin/benefits/r-32/images/pic_r-32_what_sp-jpg.jpg?rev=-1&hash=D646B34153D21EB7BF4437FC21F34377",
    "https://scx2.b-cdn.net/gfx/news/hires/2023/preparing-the-stage-fo.jpg",
    "https://i.pinimg.com/736x/53/ee/da/53eedacc1ef33a8a930e770180d020e1--most-efficient-solar-panels-solar-panels-for-home.jpg",
    "https://i.ytimg.com/vi/exHJ_ky4KUg/maxresdefault.jpg",
    "https://i.pinimg.com/originals/9f/cf/8e/9fcf8e277c73eca85bb8b70b905e1f37.jpg",
    "https://www.semiconductor-digest.com/wp-content/uploads/2024/05/Screen-Shot-2024-05-23-at-2.40.43-PM-1024x657.png",
    "https://i.ytimg.com/vi/77-NutWGR74/maxresdefault.jpg",
    "https://i.ytimg.com/vi/BiemOdLYf48/maxresdefault.jpg",
    "https://i.ytimg.com/vi/DLYaK6AYWRY/maxresdefault.jpg",
    "https://i.ytimg.com/vi/Gprc9Bhbiy4/maxresdefault.jpg",
    "https://image.slidesharecdn.com/nidecautomotivemotoramericas-130807003445-phpapp01/95/nidec-automotive-motor-americas-5-638.jpg?cb=1476677133",
    "https://img.directindustry.com/images_di/photo-mg/15283-15117649.jpg",
    "https://i.pinimg.com/originals/45/9f/de/459fdec787f43751fef048a3efe73c07.png",
    "https://i.ytimg.com/vi/fjyLzBoOz6U/maxresdefault.jpg",
    "https://web-material3.yokogawa.com/1/79/overview/computers_dcs_image.jpg",
    "https://www.azbil.com/products/building/building-automation-controls/building-management-systems/savic-net-g5/image/screen_08.jpg",
    "https://www.kitz.com/en/cms/wp-content/uploads/2024/09/high-pressure-H2-valve_.jpg",
    "https://www.pumpsebara.com/wp-content/uploads/SPD-2-800x533.jpg",
    "https://www.kuraray.com/uploads/5c3da63105eb6/100208_2_l.jpg",
    "https://i.ytimg.com/vi/LeY1PU0jEtw/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGkgaShpMA8=&amp;rs=AOn4CLBDluv0TsmAv61G3YuHvuW4UtocMw",
    "https://www.tevonews.com/images/TEIJIN.jpg",
    "https://www.manufacturingtodayindia.com/cloud/2024/05/27/lbk4itRD-The-new-assembly-plant-for-Planova%E2%84%A2-filters-1200x900.jpg",
    "https://i.ytimg.com/vi/z_s1wkz25iI/maxresdefault.jpg",
    "https://play-lh.googleusercontent.com/HM_E_5RwS90FFWuOPVkwSMRfVnxaYPg401biWiTsJLneyfLsYxPuAGJS3VShmXqbG2s",
    "https://scx2.b-cdn.net/gfx/news/2024/this-picture-taken-on-1.jpg",
    "https://www.pcbaaa.com/wp-content/uploads/2023/03/shin-etsu-company.webp",
    "https://www.mitsubishielectric.com/fa/our-stories/012/img/img_04.jpg",
    "https://www.winchestersun.com/wp-content/uploads/sites/44/2018/09/A1-091518-Sekisui-7234.jpg",
    "https://i.pinimg.com/736x/44/0c/8c/440c8c075375a460b90e984af1f50774.jpg",
    "https://i.ytimg.com/vi/cpKrHMQ1xis/maxresdefault.jpg",
    "https://www.ricoh-ap.com/news/2023/01/19/-/media/all-regional/images/discover/medi/2023/01/joji-visit-in-dec-2022/joji-6.png",
    "https://i.pinimg.com/originals/50/d2/4a/50d24a7a14ee17fd64257501d57a3a90.jpg",
    "https://www.nessancleary.co.uk/wp-content/uploads/2022/02/Canon_VenloInk_PRcan_WQ.jpg",
    "https://www.nikon.com/company/technology/product/semiconductor/img/pic_semiconductor_02.jpg"
  ];

  for (let i = 0; i < 60; i++) {
    allArticles.push({
      title: businessTitles[i],
      content: `${businessTitles[i]}に関する詳細な分析記事です。\n\n## 市場動向と背景\n\n現在の市場環境において、この取り組みは非常に重要な意味を持っています。業界全体のトレンドと企業戦略の観点から、この動きを詳しく分析します。\n\n## 技術的革新\n\n最新の技術を活用したこの取り組みは、従来の課題を解決し、新たな価値創造を実現します。技術的な詳細と実装方法について解説します。\n\n## 経済効果と将来展望\n\n投資規模と期待される経済効果、そして中長期的な市場への影響について詳しく分析します。競合他社の動向も含めて総合的に評価します。\n\n## まとめ\n\nこの取り組みが業界に与える影響と、今後の展開について総括します。`,
      excerpt: `${businessTitles[i].substring(0, 100)}...`,
      imageUrl: businessImages[i],
      tags: ["ビジネス", "企業戦略", "技術革新", "市場分析"],
      category: "BUSINESS",
      slug: `business-${String(i + 1).padStart(3, '0')}`,
      author: ["田中太郎", "佐藤花子", "山田次郎", "編集部"][i % 4],
      viewCount: Math.floor(Math.random() * 5000) + 500,
      isPublished: true
    });
  }

  // テクノロジー記事60本 - 完全にユニークなデータ
  const technologyTitles = [
    "OpenAI、GPT-5の開発を正式発表。AGI実現に向けた重要なマイルストーン",
    "Google、量子コンピューター「Willow」で計算速度1000倍向上を達成",
    "Meta、脳波制御VRヘッドセット開発。思考だけでメタバース操作が可能に",
    "Tesla、完全自動運転レベル5を2025年に実現予定。AI技術の飛躍的進歩",
    "Microsoft、クラウドAIサービス「Azure GPT」を大幅アップデート",
    "Apple、AR眼鏡「Apple Glass」の量産開始。日常生活にAR技術を統合",
    "NVIDIA、次世代AIチップ「H200」で推論性能10倍向上を実現",
    "Amazon、音声AI「Alexa 3.0」で自然な会話能力を大幅強化",
    "IBM、1000量子ビット超のプロセッサ「Quantum Condor」を発表",
    "Intel、3nmプロセス技術で半導体性能の新記録を樹立",
    "Samsung、8K有機ELディスプレイの量産技術を確立",
    "Sony、次世代ゲーム機「PS6」でリアルタイムレイトレーシング実現",
    "Adobe、AI動画生成ツール「Firefly Video」をリリース",
    "Salesforce、CRM業務を完全自動化するAIアシスタント開発",
    "Oracle、自律型データベース技術で運用コスト90%削減を実現",
    "Cisco、6G通信技術の実証実験で100Gbps通信速度を達成",
    "Qualcomm、スマートフォン向け5nmAIチップの量産開始",
    "AMD、データセンター向けCPUで省電力性能を50%向上",
    "Arm、IoT機器向け超低消費電力プロセッサを開発",
    "Broadcom、光通信チップで800Gbps伝送速度を実現",
    "Micron、次世代メモリ技術「HBM4」の開発完了",
    "Western Digital、100TB容量のSSDを商用化",
    "Seagate、ヘリウム充填HDD技術で容量30TB達成",
    "NetApp、AI最適化ストレージシステムを発表",
    "VMware、仮想化技術の次世代プラットフォーム開発",
    "Red Hat、Kubernetes管理の完全自動化ツール提供",
    "Docker、コンテナセキュリティの革新技術を実装",
    "GitHub、AI支援プログラミングツール「Copilot X」をリリース",
    "GitLab、DevOpsパイプラインの完全自動化を実現",
    "Atlassian、チーム協働AIアシスタント「Jira AI」を発表",
    "Slack、音声認識による会議自動要約機能を追加",
    "Zoom、リアルタイム言語翻訳機能を全プランに標準搭載",
    "Teams、ホログラム会議機能でリモートワークを革新",
    "Discord、ゲーム内AI音声チャット機能を実装",
    "Spotify、AI作曲機能でパーソナライズ音楽生成",
    "Netflix、視聴者の感情を読み取るAI推薦システム開発",
    "YouTube、AI動画編集ツールでクリエイター支援強化",
    "TikTok、リアルタイムAR効果生成技術を実装",
    "Instagram、AI写真補正機能を大幅アップデート",
    "Twitter、偽情報検出AIシステムの精度を95%まで向上",
    "LinkedIn、AI転職マッチングサービスの精度向上",
    "Facebook、メタバース内AI翻訳機能を実装",
    "WhatsApp、エンドツーエンド暗号化の量子耐性を強化",
    "Telegram、AI搭載チャットボット機能を全ユーザーに開放",
    "Signal、プライバシー保護AI機能を新たに実装",
    "Uber、完全自動運転タクシーサービスを都市部で開始",
    "Lyft、AI需要予測システムで待ち時間50%短縮",
    "Airbnb、AI宿泊体験最適化システムを導入",
    "Booking.com、旅行計画AI「Trip Genius」をリリース",
    "Expedia、音声対話型旅行予約システムを実装",
    "DoorDash、ドローン配送サービスを主要都市で開始",
    "Grubhub、AI料理推薦システムで注文満足度向上",
    "Instacart、店内ナビゲーションAIロボットを導入",
    "Amazon Fresh、完全無人店舗技術を全店展開",
    "Walmart、在庫管理AIシステムで欠品率90%削減",
    "Target、パーソナライズショッピングAIを実装",
    "Best Buy、AR試着システムで家電購入体験を革新",
    "Home Depot、DIYプロジェクトAIアドバイザーを提供",
    "Lowe's、建築設計AIツールで住宅改修を支援",
    "IKEA、AR家具配置アプリの精度を大幅向上"
  ];

  const technologyImages = [
    "https://i.ytimg.com/vi/V3XcrVI3fL4/maxresdefault.jpg",
    "https://i.ytimg.com/vi/NB9K4CoYSIM/maxresdefault.jpg",
    "https://i.ytimg.com/vi/mHY4QoyQAVU/maxresdefault.jpg",
    "https://cdn-images-1.medium.com/max/1600/1*vVTVcKTNyAIVgum_2HH10g.png",
    "https://i.ytimg.com/vi/UzjbKjUOQnQ/maxresdefault.jpg",
    "https://i.pinimg.com/originals/37/68/f9/3768f97a774b3d33a338692d54cc7b57.png",
    "https://lh7-us.googleusercontent.com/1DQSkomlW9plHDC4xb71x4GtZ6sasTITU-4mNKr6uLp5aolA9Xz8QmqBNW2_GGypXelKrLhc6Xxp5cuHI8EHTilMNJTrGqrgacBHFn46Qz5Qzlqk8lz9FtyoPSTyhJP1kLmUMQalcKnQEzq2kRH9VkI",
    "https://voicebot.ai/wp-content/uploads/2016/09/blackfinn360-amazon-alexa-user-experience.jpg",
    "https://i.ytimg.com/vi/5-HvdcBbV58/maxresdefault.jpg",
    "https://i.ytimg.com/vi/WVLGKq9An28/maxresdefault.jpg",
    "https://www.gizmochina.com/wp-content/uploads/2021/01/samsung-90hz-oled-laptop-display-1920x1280.jpg",
    "https://i.ytimg.com/vi/8Bm_Rcyvn60/maxresdefault.jpg",
    "https://i.ytimg.com/vi/J4-xK0aralc/maxresdefault.jpg",
    "https://www.salesforce.com/content/dam/blogs/us/August2015/Sales%20Dashboard.png",
    "https://i.ytimg.com/vi/f3RJd7nBlts/hqdefault.jpg",
    "https://as2.ftcdn.net/v2/jpg/09/18/14/51/1000_F_918145197_Xm2qYwmQTFGYzCOaAngoysuhbA8AqHSC.jpg",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj6C8TSrJoKcHqDz4kGyFquQvL80zCrYdRXxgURrugaPD8HKIMTHztu5nQ_m97M_6o6gNhH_ABdDuDls4XOG9cNKhtvjhqDV2G4UFAM1U_Nq-qv0S9wXR7D2SHvT2jaS4SuMHfoiQkir_Dt/s800/qualcomm-snapdragon-888.png",
    "https://abgeeauzno.cloudimg.io/v7/pokde.net/assets/uploads/2022/11/epycgenoacover.png?org_if_sml=0",
    "https://www.zdnet.com/a/hub/i/r/2016/02/23/bbb29f7b-b888-4013-b657-efe6876d6f1a/resize/770xauto/79104d8f10816ae8595ef1aa839cf920/cortex-a32.jpg",
    "https://www.servethehome.com/wp-content/uploads/2024/08/Broadcom-AI-ASIC-with-Optical-Connect-Hot-Chips-2024_Page_14.jpg",
    "https://yunpan.cdn.site.joinf.com/5469324759847321/cwWxQmx6G60.13302003789394878",
    "https://digital.bg/wp-content/uploads/2016/12/0915e36988117972aced93b5711dd16e.jpg",
    "https://i.ytimg.com/vi/JNGsTHuFcvM/maxresdefault.jpg",
    "https://i.pinimg.com/originals/8c/48/9e/8c489eea794ab7f1dfd60a21050df1c8.jpg",
    "https://i.ytimg.com/vi/84qlze5AYLs/maxresdefault.jpg",
    "https://content.cloudthat.com/resources/wp-content/uploads/2022/12/intro-1-1024x707.png",
    "https://images.idgesg.net/images/article/2017/06/docker-architecture-100726627-large.jpg",
    "https://codeandhack.b-cdn.net/wp-content/uploads/2022/06/GitHub-Copilot-AI-Based-Programming-Assistant-1152x605.jpg",
    "https://about.gitlab.com/images/blogimages/Beautifying-of-our-ui-16-1/pipeline-index-page-after.png",
    "https://wac-cdn.atlassian.com/dam/jcr:d42e8c86-a14b-4ec0-8753-d30c65dce581/Dashbaords-view.png?cdnVersion=1413",
    "https://lh3.googleusercontent.com/CsvGBiFdaV4i_xUpxtJmtQNxxB4_KK7Ik9qdLsLsVM56p-wKBOV3geBW4y8lHfanVdAt8sEbH_-A8N-lF4FWAEEWg7izcRPZi3dpq5GxhPjPQbuE1trNrAg6FqoxuhNqYAjCsHr_3p_t8dssRE1HhTM",
    "https://i.ytimg.com/vi/1Q4YgmiTE2E/maxresdefault.jpg",
    "https://www.microsoft.com/en-us/dynamics-365/blog/wp-content/uploads/2022/12/TeamsInGuides-OverviewImage.jpg",
    "https://i.ytimg.com/vi/b9DUAMT9phU/maxresdefault.jpg",
    "https://static1.makeuseofimages.com/wordpress/wp-content/uploads/2023/06/spotify-ai-playlist-art-website.jpg",
    "https://lh5.googleusercontent.com/V_zpXxijvovME-YVCQ1S4JczNpW2Kcdqp0pFwcCbYS7D3DusOByFifuUTt8jLUa1WVmCmcPXVK1pvrXs_tOOiv_QukorKDhs2NrvihjjNLXF0S0UEizyUf_LG5kQly20J17UkMO6U2B2huaDc65UXAw",
    "https://i.ytimg.com/vi/5xmp8NQIMQ4/maxresdefault.jpg",
    "https://i.ytimg.com/vi/deHvURmgMSY/maxresdefault.jpg",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgSXkDOhuAjXJjgkRGvXlUrkbImQeZYAq7z8BPizjLksb9M_7jMaGP1NfQShUJLg-g8mKvQXNK8kzUr3NiUwWg1Iq9rWjP6Jb4DQUyepXCrD9IVqQ2pwMPcaXTNd31Ohh8ACRU7bU2AsogaztUafejY7ja7t8KI1I3uAtyxx52vWHRQRmOg4Ka0tJRvJw/w1600/IG-Nav-2023.webp",
    "https://images.deepai.org/publication-preview/covidmis20-covid-19-misinformation-detection-system-on-twitter-tweets-using-deep-learning-models-page-13-medium.jpg",
    "https://opengraph.githubassets.com/253178eabcce89f893ab99979a326b0a5f32197659a08cd3ed51a53b7f239fad/NeroJ/Job-Matching-AI-",
    "https://i.ytimg.com/vi/yoRQz_L3Dfg/maxresdefault.jpg",
    "https://media.licdn.com/dms/image/v2/D4D12AQHZsSrHil2cGA/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1724996456749?e=2147483647&v=beta&t=7cyB0OKIWTNcf02jqJqRPF9nplmI_jE2QdnO2VXBtqg",
    "https://i.ytimg.com/vi/hlhe_RbUuAM/maxresdefault.jpg",
    "https://i.ytimg.com/vi/cQs55PZdl-s/maxresdefault.jpg",
    "https://static.designboom.com/wp-content/uploads/2024/08/uber-autonomous-taxis-self-driving-AI-cars-wayve-cruise-designboom-500.jpg",
    "https://cdn-images-1.medium.com/max/839/0*lIdeth69zGCfdrcp.png",
    "https://i.pinimg.com/originals/45/76/fb/4576fb7e377923de4db2313e374d5407.png",
    "https://content.presspage.com/uploads/685/ad93ac95-a3d5-459d-85ea-9c0e09334e5a/1920_booking.com-aitripplanner.jpg?10000",
    "https://i.ytimg.com/vi/FeKHZBufM4E/maxresdefault.jpg",
    "https://i.ytimg.com/vi/seiI9wB23Fo/maxresdefault.jpg",
    "https://lh7-us.googleusercontent.com/c0Y_9vCPlaHCm8Nwrf8IwpQHYzeZyJKk5oH-H13VJMC7tRWouHvKKBeBhejFX2f-CkRW4_ZQBL8oynUHVp41XYq-p0Ez0ltEs8homDanov5uIR-VR-qZoBpKBfCZqRbjKct7enrwJbLpt7klARaD08E",
    "https://foodondemand.com/wp-content/uploads/2023/06/Screen-Shot-2023-06-28-at-10.05.24-AM-1080x675.png",
    "https://img.theepochtimes.com/assets/uploads/2021/06/18/cashierless-technology-amazon-fresh-in-wash.-1200x808.jpg",
    "https://i.pinimg.com/originals/d5/da/e8/d5dae8e9bf4060591c8e7e4bc5f7b3fc.jpg",
    "https://www.flyfish.ai/wp-content/uploads/2024/03/Crafting-Personalized-Shopping-Journeys-with-Generative-AI.jpg",
    "https://pbs.twimg.com/media/FvYLpiiaUAEFMTd.jpg",
    "https://i.pinimg.com/originals/5a/ac/03/5aac03cdb27d890c45faca0311384e37.jpg",
    "https://i.ytimg.com/vi/FugJyCilScQ/maxresdefault.jpg",
    "https://itwire.com/images/articles/IKEA-Place-1.jpg"
  ];

  for (let i = 0; i < 60; i++) {
    allArticles.push({
      title: technologyTitles[i],
      content: `${technologyTitles[i]}に関する最新技術動向の詳細分析です。\n\n## 技術的ブレークスルー\n\nこの技術革新は従来の限界を突破し、新たな可能性を切り開いています。技術的な詳細と実装方法について詳しく解説します。\n\n## 産業への影響\n\n各産業分野への波及効果と、ビジネスモデルの変革について分析します。競合技術との比較も含めて総合的に評価します。\n\n## 将来展望\n\n中長期的な技術発展の方向性と、社会に与える影響について予測します。課題と解決策についても詳しく検討します。\n\n## 結論\n\nこの技術革新が業界と社会に与える変革の意義について総括します。`,
      excerpt: `${technologyTitles[i].substring(0, 100)}...`,
      imageUrl: technologyImages[i],
      tags: ["テクノロジー", "AI", "イノベーション", "デジタル変革"],
      category: "TECHNOLOGY",
      slug: `technology-${String(i + 1).padStart(3, '0')}`,
      author: ["鈴木一郎", "高橋美咲", "伊藤健太", "編集部"][i % 4],
      viewCount: Math.floor(Math.random() * 5000) + 500,
      isPublished: true
    });
  }

  // マネー記事60本 - 完全にユニークなデータ
  const moneyTitles = [
    "日銀、政策金利を0.5%に引き上げ。17年ぶりの大幅利上げで円高進行",
    "新NISA制度開始から1年。投資残高が30兆円突破で個人投資家急増",
    "ビットコイン価格が史上最高値更新。機関投資家の参入で1000万円突破",
    "東京証券取引所、AI取引システム導入で取引効率50%向上",
    "三菱UFJ銀行、デジタル通貨「MUFG Coin」の本格運用開始",
    "野村證券、ロボアドバイザーサービスで運用資産10兆円達成",
    "SBI証券、手数料完全無料化で個人投資家の取引量3倍増",
    "楽天証券、AI投資助言サービスで顧客満足度95%達成",
    "マネックス証券、暗号資産取引プラットフォームを大幅強化",
    "大和証券、ESG投資ファンドで運用残高5兆円突破",
    "みずほ銀行、ブロックチェーン決済システムの商用化開始",
    "三井住友銀行、AI融資審査システムで承認時間90%短縮",
    "りそな銀行、デジタルバンキングサービスの利用者1000万人突破",
    "ゆうちょ銀行、投資信託販売でネット取引比率80%達成",
    "新生銀行、フィンテック企業との提携で新サービス展開",
    "住信SBIネット銀行、AI家計管理アプリで利用者急増",
    "ソニー銀行、外貨預金サービスで手数料大幅削減",
    "イオン銀行、店舗内ATMの完全キャッシュレス化実現",
    "セブン銀行、スマホATMサービスで取引件数倍増",
    "PayPay銀行、デジタル融資サービスで即日審査を実現",
    "LINE証券、若年層向け投資教育プログラムを本格展開",
    "ネオモバイル証券、1株投資サービスで投資初心者獲得",
    "CONNECT、スマホ完結型証券サービスで差別化",
    "STREAM、手数料無料株式取引で市場シェア拡大",
    "One Tap BUY、米国株投資の簡素化で利用者増加",
    "フォリオ、テーマ投資サービスで個性的なポートフォリオ提供",
    "ウェルスナビ、ロボアドバイザーで運用資産1兆円達成",
    "THEO、AI資産運用サービスで顧客基盤拡大",
    "楽ラップ、低コスト運用で投資初心者に人気",
    "マネックスアドバイザー、パーソナライズ投資助言を強化",
    "クレディセゾン、キャッシュレス決済で取扱高50%増",
    "三井住友カード、タッチ決済普及で利用率90%達成",
    "JCB、海外決済ネットワーク拡大でシェア向上",
    "アメリカン・エキスプレス、プレミアムサービス強化",
    "ダイナースクラブ、富裕層向けサービスで差別化",
    "楽天カード、ポイント経済圏拡大で会員数2500万人突破",
    "イオンカード、電子マネーWAON連携で利便性向上",
    "dカード、ドコモ経済圏との連携強化で利用促進",
    "au PAYカード、通信キャリア連携で競争力強化",
    "ソフトバンクカード、PayPay連携で決済シェア拡大",
    "メルペイ、フリマアプリ連携で独自の決済体験提供",
    "LINE Pay、韓国発の決済技術で差別化",
    "d払い、QRコード決済で加盟店数100万店突破",
    "au PAY、通信料金との合算決済で利便性向上",
    "ファミペイ、コンビニ連携で独自のサービス展開",
    "ゆうちょPay、郵便局ネットワーク活用で地方展開",
    "Bank Pay、銀行直結決済で安全性をアピール",
    "J-Coin Pay、みずほ主導の決済サービスで企業向け強化",
    "pring、個人間送金サービスで若年層獲得",
    "Kyash、バーチャルカード技術で新体験提供",
    "マネーフォワード、家計簿アプリで金融データ活用",
    "freee、中小企業向け会計ソフトで市場拡大",
    "弥生、クラウド会計サービスで業務効率化支援",
    "勘定奉行、AI会計システムで経理業務革新",
    "PCA、中堅企業向けERPシステム強化",
    "オービック、大企業向け基幹システムで競争力維持",
    "TKC、税理士向けシステムで専門性強化",
    "ミロク情報サービス、地方企業向けサービス拡充",
    "応研、建設業向け専門システムで特化戦略",
    "ソリマチ、農業向け会計システムで新市場開拓"
  ];

  const moneyImages = [
    "https://static01.nyt.com/images/2024/03/19/business/19boj-promo/19boj-promo-videoSixteenByNineJumbo1600.png",
    "https://i.pinimg.com/originals/02/d8/b4/02d8b4ac2e14434df32d8710ab00717f.png",
    "https://i.pinimg.com/736x/07/d0/d2/07d0d22e722396a9c0bce611bb56aa55.jpg",
    "https://i.ytimg.com/vi/sLO-ZKUs4lM/maxresdefault.jpg",
    "https://www.ledgerinsights.com/wp-content/uploads/2023/09/progmat-stablecoin-binance-mufg.2.jpg",
    "https://appinventiv.com/wp-content/uploads/2024/01/Robo-Advisor-Platform-Development-Costs-Benefits-and-Process-for-FinTech-Businesses_Info_6.webp",
    "https://i.ytimg.com/vi/dmWIKQhuRS8/maxresdefault.jpg",
    "https://i.ytimg.com/vi/fhYh0Rc-94E/maxresdefault.jpg",
    "https://i.pinimg.com/originals/77/27/a9/7727a9e56c645047e5c6c9eeb4d8b2fb.png",
    "https://www.daiwa-securities-living.co.jp/wp-content/uploads/2022/05/de2677dacee8eb84733acea80533e3fa.png",
    "https://www.nfcw.com/wp-content/uploads/2020/10/fujitsu-jcb-digital-id-platform-diagram.jpg",
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/SMBC_Head_Office_Building.JPG/800px-SMBC_Head_Office_Building.JPG",
    "https://play-lh.googleusercontent.com/S6Siqv1JbFs-BaIXG31Qu3ooY8OeW5rue7Tqz1SDtT0giWm4JAsqmj2h-g2Ni506WQ",
    "https://i.ytimg.com/vi/XdWnkQ0MOLs/maxresdefault.jpg",
    "https://c8.alamy.com/comp/PWP7NK/tokyo-japan-17th-oct-2018-japans-shinsei-bank-president-hideyuki-kudo-announces-shinsei-bank-ntt-docomo-and-money-foward-will-start-lending-service-using-fintech-tenhnology-in-tokyo-on-wednesday-october-17-2018-they-will-start-loaning-service-to-docomos-users-from-next-march-credit-yoshio-tsunodaafloalamy-live-news-PWP7NK.jpg",
    "https://pbs.twimg.com/media/Fmpv9CgaEAEUJF1.jpg",
    "https://moneykit.net/en/fx/img/fx45/main_sp.png",
    "https://lh3.googleusercontent.com/ZfnEI09lmnMD08XnnZJqJijphPUtW_2zw713mY1iVZkntSPEG5xYFN-ZHv0LkRBx=w1080-k-no",
    "https://i.ytimg.com/vi/Yg6z1_RuDh4/maxresdefault.jpg",
    "https://lh7-us.googleusercontent.com/2eIVRbZrN-nAEYSK8cr7ACEk50oOJUqr7ptvtsFGwgEECFjrGudJbQvLT0zHvrU3GbaN0iiO3KJ413-VS-gtKgP0mbTAmtXDRL7fXMiAfi0HvkjZb1jSZfsuJyBmsWbnMy3SOxz8V4PCiKF3v-pdwjo",
    "https://media.licdn.com/dms/image/D4D22AQE7rel4sfZPdg/feedshare-shrink_2048_1536/0/1688994585860?e=2147483647&v=beta&t=0GuabX3eKFO3x9RuTpMs86_LigoRH7V195idojBFr30",
    "https://play-lh.googleusercontent.com/VJ5e3izPRFjOESnDvBSDeMV1KOf9w_1z_CfdQO5YukHI9GkAU3MueOOVK559arMUCA",
    "https://thumbs.dreamstime.com/z/businessmen-use-smartphones-to-connect-data-authentication-privacy-devices-online-security-protection-technology-255924579.jpg",
    "https://i.pinimg.com/736x/bf/fb/ca/bffbca97ce4b8b572e4b1472f7af0d9a.jpg",
    "https://i.ytimg.com/vi/S8IM4DHx38M/maxresdefault.jpg",
    "https://www.slideteam.net/media/catalog/product/cache/1280x720/i/n/investment_fund_portfolio_selection_strategy_ppt_powerpoint_presentation_portfolio_example_cpb_slide01.jpg",
    "https://media.licdn.com/dms/image/sync/D5627AQEsC3qX7Ha0pA/articleshare-shrink_800/0/1721780593323?e=2147483647&v=beta&t=NIALjIFl7w7d632hwO4BOUN6Yc2ces5Ho80NltAG3j4",
    "https://i.pinimg.com/originals/36/12/9c/36129c7d3d27d67e02bf6db340add0af.png",
    "https://i.ytimg.com/vi/goRHZBF1At0/maxresdefault.jpg",
    "https://images.brightmoney.co/blogs/2-personalized-investment-advice-to-know.png",
    "https://i.ytimg.com/vi/tqhOWOF5JWw/maxresdefault.jpg",
    "https://www.shutterstock.com/shutterstock/photos/2215449173/display_1500/stock-photo-boston-ma-the-visa-gold-card-from-smbc-sumitomo-mitsui-bank-corporation-modern-card-2215449173.jpg",
    "https://i.pinimg.com/originals/39/23/03/392303b80a0543d82972c1c5d090c9d9.jpg",
    "https://milestomemories.com/wp-content/uploads/2020/07/UK-british-airways-card-offers-1536x1044.png",
    "https://www.dinersclub.com/content/dam/discover/en_us/diners-club/images/home/red-diners-club-card.png",
    "https://i0.wp.com/rakuten.today/wp-content/uploads/2022/07/Rakuten-Ecosystem.png?fit=1024%2C576&ssl=1",
    "https://www.waon.net/sp/language/en/about/images/step_02.jpg",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhOiTM8hLk-JCgmt8GEYqpnuZ49F2MGa0ED5hdLQHyK32-F3Xg9OG8aK0_hYc1n4L1LBeLV3RNChRfctWpxkLK1osr54uZrzAMMlD-hvt8_wfEZtl8AWyFc4Kyr8RCrr9YU9dM45XV4ExqJaGoWLMXlo3EOlqChlUWu5KCl6g-4s5hRcNxpViLVert1/w1200-h630-p-k-no-nu/Docomo_OREC_vRAN.jpg",
    "https://pbs.twimg.com/media/FkZOpVXUYAAwXVx.png",
    "https://i.ytimg.com/vi/MskoNwN4V_c/maxresdefault.jpg",
    "https://en.komoju.com/wp-content/uploads/2024/06/Picture11.jpg",
    "https://i.ytimg.com/vi/gM7m3p7nODU/maxresdefault.jpg",
    "https://i.ytimg.com/vi/e1PFOUI027A/maxresdefault.jpg",
    "https://pbs.twimg.com/media/Dzda40NWwAEx8rC.jpg:large",
    "https://www.family.co.jp/content/dam/family/services/payment/famipay/famipay_pay_520300_2.png",
    "https://pbs.twimg.com/media/FeS0yCnaAAAOIBs?format=jpg&name=large",
    "https://www.barclays.co.uk/content/dam/lifestyle-images/personal/ways-to-bank/mobile_banking_payments_app_3_1.jpg",
    "https://www.mizuhogroup.com/binaries/content/gallery/mizuhoglobal/news/2019/03/20190304release_eng_1.jpg",
    "https://i.pinimg.com/originals/a6/a7/b7/a6a7b7b74f2c1e3b3775061cc69b82d1.jpg",
    "https://i.ytimg.com/vi/WJTuwk0qHf8/maxresdefault.jpg",
    "https://i.ytimg.com/vi/EHdKYs6muks/maxresdefault.jpg",
    "https://i.ytimg.com/vi/HhyXnNaGkIE/maxresdefault.jpg",
    "https://play-lh.googleusercontent.com/CYwQifQ31Hi8LY0CvDFrPxlEtaNjyx537kyI7J0HfCfm-FdVEpo-ZdIVx1UN7cHqpqQ=w526-h296",
    "https://www.xeex.co.jp/images/handling-solutions/kanjo-bugyo-i/image003.png",
    "https://i.ytimg.com/vi/YyfYVhbzCRY/maxresdefault.jpg",
    "https://corp.obc.co.jp/hubfs/corp/images/en/ir/policy/vision/vision_img_01.jpg",
    "https://pdf.wondershare.jp/images/images2021/articles/tax-tkc-system-04.jpg",
    "https://img.cointime.com/images/w6DdHB9EIn2B5qOarbFr6Kok04ZKcuYN3e2Avk5V.jpg",
    "http://www.ohken.co.jp/recruit/img/common/ogp.png",
    "https://i.ytimg.com/vi/ZuvhIITVNuw/hqdefault.jpg"
  ];

  for (let i = 0; i < 60; i++) {
    allArticles.push({
      title: moneyTitles[i],
      content: `${moneyTitles[i]}に関する金融市場の詳細分析です。\n\n## 市場動向と背景\n\n現在の金融環境における重要な動きとして、この発表は市場に大きな影響を与えています。マクロ経済の観点から詳しく分析します。\n\n## 投資戦略への影響\n\n個人投資家および機関投資家の投資戦略に与える影響について詳しく解説します。リスク評価と収益機会の両面から検討します。\n\n## 今後の展望\n\n中長期的な市場動向と投資機会について予測します。規制環境の変化や技術革新の影響も含めて総合的に評価します。\n\n## 投資家へのアドバイス\n\nこの動きを受けた具体的な投資戦略と注意点について実践的なアドバイスを提供します。`,
      excerpt: `${moneyTitles[i].substring(0, 100)}...`,
      imageUrl: moneyImages[i],
      tags: ["金融", "投資", "資産運用", "市場分析"],
      category: "MONEY",
      slug: `money-${String(i + 1).padStart(3, '0')}`,
      author: ["渡辺雄一", "中村さくら", "小林大輔", "編集部"][i % 4],
      viewCount: Math.floor(Math.random() * 5000) + 500,
      isPublished: true
    });
  }

  // ライフ記事60本 - 完全にユニークなデータ
  const lifeTitles = [
    "在宅勤務制度の定着で地方移住が加速。東京都の人口が3年連続減少",
    "健康寿命延伸への取り組み。予防医療市場が5兆円規模に拡大",
    "サステナブル消費が主流に。環境配慮商品の市場シェアが30%突破",
    "デジタルデトックスブーム到来。アナログ体験重視のライフスタイル拡大",
    "ペット共生社会の実現。高齢者向けペットケアサービスが急成長",
    "食品ロス削減運動が本格化。家庭での廃棄量50%削減を達成",
    "ミニマリストライフの普及。断捨離サービス市場が1000億円規模に",
    "ワーケーション文化の定着。地方自治体の誘致競争が激化",
    "シニア世代のデジタル活用。60代以上のSNS利用率が80%突破",
    "子育て支援サービスの充実。共働き世帯の負担軽減が進む",
    "メンタルヘルスケアの重要性増大。カウンセリングサービス需要急増",
    "フィットネステック市場拡大。AI搭載ホームジム機器が人気",
    "オンライン学習の普及。社会人の学び直し需要が5倍増",
    "地産地消ライフスタイル。ローカルフード市場が急成長",
    "シェアリングエコノミーの浸透。所有から利用への価値観変化",
    "睡眠の質向上ブーム。スリープテック市場が2000億円規模に",
    "プラントベース食品の普及。代替肉市場が年率30%成長",
    "DIY文化の復活。手作り体験サービスが若年層に人気",
    "マインドフルネス実践者急増。瞑想アプリ利用者が1000万人突破",
    "アウトドアライフの人気拡大。キャンプ用品市場が過去最高",
    "高齢者向けスマートホーム。IoT技術で安全な一人暮らしを支援",
    "フードテック革命。培養肉技術の実用化が本格始動",
    "リモートワーク環境整備。ホームオフィス市場が3倍拡大",
    "エシカル消費の浸透。フェアトレード商品の売上が倍増",
    "ウェルネスツーリズム人気。健康重視の旅行スタイルが定着",
    "デジタル終活サービス。高齢者のデジタル資産管理支援",
    "コミュニティガーデン運動。都市部での共同菜園が急増",
    "ゼロウェイストライフ。廃棄物ゼロを目指すライフスタイル拡大",
    "バーチャルリアリティ体験。高齢者の認知症予防に活用",
    "サブスクリプション生活。定額制サービス利用が日常化",
    "クラフトビール文化。地域密着型醸造所が全国に拡大",
    "アーバンファーミング。都市部での農業体験が人気",
    "ソーシャルグッド消費。社会貢献型商品の購入意欲向上",
    "デジタルノマド増加。場所に縛られない働き方が拡大",
    "ペットテック市場成長。AI搭載ペット用品が注目",
    "リユース文化の定着。中古品市場が新品市場を上回る成長",
    "ホームスクーリング選択。教育の多様化が進む",
    "グランピング人気継続。豪華キャンプ体験施設が急増",
    "フレキシタリアン増加。柔軟な菜食主義者が主流に",
    "デジタルウェルビーイング。テクノロジーと健康の両立",
    "コワーキングスペース進化。地域コミュニティの拠点に",
    "サーキュラーエコノミー実践。循環型経済への参加意識向上",
    "インクルーシブデザイン普及。誰もが使いやすい製品設計",
    "ローカルツーリズム拡大。近場旅行の魅力再発見",
    "デジタルファスティング。定期的なネット断食が習慣化",
    "コミュニティ支援型農業。消費者と生産者の直接つながり",
    "エイジングインプレイス。住み慣れた地域での高齢期生活",
    "バイオフィリックデザイン。自然要素を取り入れた住環境",
    "ソーシャルイノベーション。社会課題解決型ビジネス拡大",
    "デジタルリテラシー教育。全世代対象の情報活用能力向上",
    "レジリエンス向上。困難に対する回復力強化への関心",
    "コンパッショネート消費。思いやりのある消費行動拡大",
    "ハイブリッドワーク定着。オフィスと在宅の最適な組み合わせ",
    "ジェンダーニュートラル。性別にとらわれない商品・サービス",
    "カーボンニュートラル生活。個人レベルでの脱炭素実践",
    "デジタルヘルス活用。健康管理のデジタル化進展",
    "インタージェネレーション。世代間交流プログラム拡大",
    "マイクロアドベンチャー。日常に小さな冒険を取り入れる",
    "サステナブルファッション。環境配慮型衣料品の普及",
    "ニューロダイバーシティ。脳の多様性を活かす社会づくり"
  ];

  const lifeImages = [
    "https://i.ytimg.com/vi/m_Jzd_1c5cA/maxresdefault.jpg",
    "https://img.freepik.com/premium-photo/elderly-person-using-wearable-health-monitoring-device-home-facility_38013-89905.jpg",
    "https://i.pinimg.com/originals/3c/a6/bc/3ca6bc7e46db6c504c48117590895847.jpg",
    "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi1dyQrtG7NwQbxPNsGrZJrgb7pm-4RKW9mDjcCCn_M9pkcdElGkYR-XGPGiAt8Wqfm-RYZht0OBWbO_xp1XfzFp7g_O8WW-FlJ4jlPP-nrTbUYQ5X88plKxGcmaC1wUWItBYM_oABA9A2LiYHY8I37D8pVfdA_vh-g_oWpqiBrOBwN2Us1mmYrxlZtJ4o/s1024/0928b29ad4f1a4420cada09ec79be8a0_high.jpg",
    "https://i.pinimg.com/originals/41/9c/03/419c03fc90709a9d687de32c970ae094.jpg",
    "https://usedkitchenhub.com/wp-content/uploads/2020/05/food-waste.jpg",
    "https://i.pinimg.com/originals/f4/53/52/f453524c170d55acf1c6eeb426a0e06c.png",
    "https://i.pinimg.com/736x/9d/59/28/9d59289626bd6b3a3ef17c22252d162c.jpg",
    "https://media-manager.starsinsider.com/gallery/1080/na_5b3dfd99d98cb.jpg",
    "https://pbs.twimg.com/media/Fr6uF44WYAAOhS7.jpg:large",
    "https://thumbor.forbes.com/thumbor/fit-in/x/https://www.forbes.com/health/wp-content/uploads/2022/10/TS_call_image.png",
    "https://i.pinimg.com/originals/97/1f/6b/971f6bad425f60a76adfff2c226669c0.png",
    "https://thumbs.dreamstime.com/z/adult-student-taking-online-course-tablet-black-african-american-female-as-browsing-school-doing-research-146598129.jpg",
    "https://i.pinimg.com/originals/26/33/12/2633129ed1590d7fdefed1d2d739ca6c.jpg",
    "https://thumbs.dreamstime.com/b/car-sharing-service-big-smartphone-screen-mobile-app-people-ordering-cars-share-rent-flat-online-carsharing-vector-209952207.jpg",
    "http://img.banggood.com/images/oaupload/banggood/images/31/D6/a2618683-ea67-4ac5-bfee-f81dee013c30.jpg",
    "https://i.pinimg.com/originals/85/c7/8c/85c78c8440bbd088bb08126c18965e91.jpg",
    "https://i.ytimg.com/vi/ri0idD3jz8o/maxresdefault.jpg",
    "https://i.ytimg.com/vi/8f-YlqEUz6Y/maxresdefault.jpg",
    "https://i.pinimg.com/originals/c7/94/d4/c794d41244e87f7282e276da848a29ec.jpg",
    "https://i.pinimg.com/736x/8b/b5/55/8bb55557e9ce8e5438b9dc1508ddd5b7.jpg",
    "https://img.freepik.com/premium-photo/futuristic-cultured-meat-production-facility-with-lab-grown-protein-automated-bioreactors_994764-115476.jpg",
    "https://i.pinimg.com/originals/80/21/bc/8021bc7f358eab75ed6e202b8a20687a.jpg",
    "https://s-media-cache-ak0.pinimg.com/736x/4a/bf/3e/4abf3e9464cced49d1ee7a774f321893.jpg",
    "https://i0.wp.com/www.healthylivingandtravel.com/wp-content/uploads/2019/03/Mountain-Spas-Healthy-Living-Travel-1.jpg?fit=1814%2C1020",
    "https://i.ytimg.com/vi/jGEmX1YRodc/maxresdefault.jpg",
    "https://i.pinimg.com/originals/25/55/64/255564a6d5a72f1ad93d80bcfd00cede.jpg",
    "https://img.freepik.com/premium-photo/zero-waste-lifestyle-image-showcasing-reusable-containers-composting-practices-generative-ai_117038-12615.jpg",
    "https://i.ytimg.com/vi/G34FasThCgY/maxresdefault.jpg",
    "https://i.pinimg.com/originals/51/a3/5c/51a35c361108bc28ee135c79ab445acd.png",
    "https://i.pinimg.com/236x/6b/a0/5d/6ba05dd50cc98fa6e320769f4a56974f.jpg",
    "https://i.pinimg.com/originals/03/92/db/0392db78ab0ee872f1e7a1b8207d7d8c.jpg",
    "https://i.pinimg.com/originals/98/db/2c/98db2cd3806e4b1e96389c2dcda8f3b8.jpg",
    "https://img.freepik.com/premium-photo/digital-nomad-working-laptop-with-stunning-tropical-beach-as-freedom-flexibility_962751-5287.jpg?w=2000",
    "https://i.ytimg.com/vi/wzgmyrLI4VQ/maxresdefault.jpg",
    "https://i.pinimg.com/originals/58/2a/74/582a74ccda3b3c591a765374230ae0c7.jpg",
    "https://i.pinimg.com/originals/7a/e6/a0/7ae6a02bfb42622aa6bf18b79a48e349.jpg",
    "https://i.pinimg.com/originals/4b/76/31/4b7631737a22212554fa1cadd596c35e.jpg",
    "https://i.pinimg.com/originals/d6/39/37/d639374b12d2cd06ab464050e5664625.png",
    "https://i.pinimg.com/originals/06/05/55/0605558a589cc429bdea9d0d6f71645a.jpg",
    "https://i.pinimg.com/originals/62/ac/49/62ac49f086113f462eaf96f0c557540b.jpg",
    "https://i.pinimg.com/originals/3f/52/08/3f52084c6ac9fe887c1c1fb95f45117a.jpg",
    "https://community.nasscom.in/sites/default/files/styles/960_x_600/public/media/images/Accessible%20Products%20by%20Tarun%20Kumar%20Mann%20-%20Blog.png?itok=wJxom7uI",
    "https://i.pinimg.com/736x/5a/e9/6a/5ae96ae11b1aab1df69845ed491fe22d.jpg",
    "https://pbs.twimg.com/media/Fe8bm5nXgAAgZVq.jpg",
    "https://i.pinimg.com/736x/e8/11/a6/e811a66a726ae3a0301b6fef61f2f94c.jpg",
    "https://i.pinimg.com/originals/ce/a5/a8/cea5a84e1d280bc9fb6d104f9cfcfcdd.png",
    "https://i.pinimg.com/originals/a1/6c/6e/a16c6ea1cff2cc90f1079013915cb96d.jpg",
    "https://i.pinimg.com/originals/dc/fa/40/dcfa40bedf9d9581eacd76f23c97b660.jpg",
    "https://live.staticflickr.com/8822/17620602266_d105ec0652_b.jpg",
    "https://eccp.com/storage/app/uploads/public/633/3e6/7ec/thumb_3432_1024_717_0_0_fit.jpg",
    "https://compassionateshoppingguide.org/wp-content/uploads/2024/02/brand-image-0-e1578328725207.png",
    "https://smartway2.com/wp-content/uploads/2022/10/Smartway2-Flexible_office_space.jpeg",
    "https://i.pinimg.com/736x/f7/ad/e7/f7ade70843d548b9f641f8e68761a790.jpg",
    "https://dnr.maryland.gov/pprp/publishingimages/AFPA_CarbonNeutrality_Infographic_25Mar2014-01.jpg",
    "https://i.pinimg.com/originals/57/31/69/5731694504a2d6e2e41872eb388e9544.png",
    "https://www.hebrewseniorlife.org/sites/default/files/styles/width_680/public/2019-10/older_woman-finger_puppets-young_boy.jpg?itok=XfX6y8TB",
    "https://i.pinimg.com/originals/42/99/f5/4299f5637f92d073f6236d88c23da2a6.jpg",
    "https://i.pinimg.com/originals/08/14/64/08146433c96da127f7c5e456997b411b.jpg",
    "https://boyneergonomics.ie/wp-content/uploads/2022/09/ND-Adjustment-Stats-1024x1024.png"
  ];

  for (let i = 0; i < 60; i++) {
    allArticles.push({
      title: lifeTitles[i],
      content: `${lifeTitles[i]}に関するライフスタイルトレンドの詳細分析です。\n\n## 社会背景と変化\n\n現代社会における価値観の変化と、新しいライフスタイルの台頭について詳しく解説します。世代別の傾向と地域差についても分析します。\n\n## 実践方法とメリット\n\n具体的な実践方法と、それによって得られるメリットについて詳しく説明します。始めやすい方法から本格的な取り組みまで段階的に紹介します。\n\n## 課題と解決策\n\n新しいライフスタイルを実践する上での課題と、それを克服するための具体的な解決策について提案します。\n\n## 今後の展望\n\nこのトレンドの将来性と、社会全体への波及効果について予測します。持続可能性の観点からも評価します。`,
      excerpt: `${lifeTitles[i].substring(0, 100)}...`,
      imageUrl: lifeImages[i],
      tags: ["ライフスタイル", "健康", "環境", "社会変化"],
      category: "LIFE",
      slug: `life-${String(i + 1).padStart(3, '0')}`,
      author: ["松本恵子", "森田健司", "岡田みゆき", "編集部"][i % 4],
      viewCount: Math.floor(Math.random() * 5000) + 500,
      isPublished: true
    });
  }

  return allArticles;
}

export const massiveArticleData = generateUniqueArticles();
